import './globals.css'
import { Inter, Fasthand } from 'next/font/google'

//Fonts added here.............
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const fasthand = Fasthand({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-fasthand',
});

export const metadata = {
  title: 'To Do App',
  description: 'Generated by Padmesh',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${fasthand.variable}`}>{children}</body>
    </html>
  )
}
